// lib/mockData.ts
import { Nursery } from '@/types'

export const MOCK_NURSERIES: Nursery[] = [
  {
    id: 'npf-001',
    name: 'Sunflower Nursery School',
    area: 'Andersonstown',
    postcode: 'BT11 8AJ',
    address: '14 Andersonstown Road, Belfast BT11 8AJ',
    phone: '028 9062 1234',
    email: 'info@sunflower-nursery.co.uk',
    type: 'state',
    sessionType: 'part-time',
    sessions: 'Morning (9:00am–12:00pm) & Afternoon (12:30pm–3:30pm)',
    ageMin: 3,
    ageMax: 4,
    spacesAvailable: 3,
    waitlistOpen: false,
    nextIntake: 'September 2025',
    deFunded: true,
    rating: 4.8,
    lat: 54.5793,
    lng: -6.0021,
    tags: ['Sibling priority', 'Within catchment', 'State controlled'],
    admissionsCriteria: [
      { priority: 1, title: 'Children with a statement of special educational needs', description: 'Children who have a statutory statement of SEN that names this school as appropriate placement.' },
      { priority: 2, title: 'Siblings of current pupils', description: 'Children who have a brother or sister currently enrolled in Years 1–7 of the primary school attached to this nursery.' },
      { priority: 3, title: 'Children within the catchment area', description: 'Children whose home address falls within the defined catchment boundary for this school.' },
      { priority: 4, title: 'All other children', description: 'All remaining applicants, ranked by distance from home address to school gate.' },
    ],
    icon: '🌻',
    color: '#FEF3C7',
    createdAt: '2025-01-01',
    updatedAt: '2025-06-01',
  },
  {
    id: 'npf-002',
    name: 'Little Explorers Pre-School',
    area: 'Lisburn Road',
    postcode: 'BT9 7GT',
    address: '88 Lisburn Road, Belfast BT9 7GT',
    phone: '028 9066 5678',
    email: 'hello@littleexplorers.co.uk',
    website: 'https://littleexplorers.co.uk',
    type: 'integrated',
    sessionType: 'full-time',
    sessions: 'Full Day (8:00am–6:00pm)',
    ageMin: 2,
    ageMax: 4,
    spacesAvailable: 6,
    waitlistOpen: false,
    nextIntake: 'September 2025',
    deFunded: true,
    rating: 4.9,
    lat: 54.5733,
    lng: -5.9597,
    tags: ['Integrated school', 'Open enrolment', 'Extended hours'],
    admissionsCriteria: [
      { priority: 1, title: 'Children who meet funded hours criteria', description: 'Children aged 3–4 who are eligible for the DE funded pre-school programme (12.5 hrs/week).' },
      { priority: 2, title: 'Siblings of current pupils', description: 'Brothers or sisters of children currently enrolled across any year group in the school.' },
      { priority: 3, title: 'Children of staff members', description: 'Children whose parent or guardian is a permanent member of teaching or support staff.' },
      { priority: 4, title: 'All other applicants', description: 'Allocated by date of application receipt, earliest first.' },
    ],
    icon: '🔭',
    color: '#EFF6FF',
    createdAt: '2025-01-01',
    updatedAt: '2025-06-01',
  },
  {
    id: 'npf-003',
    name: 'Rainbow Garden Nursery',
    area: 'Newtownabbey',
    postcode: 'BT37 0BJ',
    address: '3 Rathcoole Drive, Newtownabbey BT37 0BJ',
    phone: '028 9085 9012',
    email: 'admin@rainbow-garden.co.uk',
    type: 'private',
    sessionType: 'part-time',
    sessions: 'Morning only (9:00am–12:00pm)',
    ageMin: 3,
    ageMax: 4,
    spacesAvailable: 0,
    waitlistOpen: true,
    nextIntake: 'January 2026',
    deFunded: true,
    rating: 4.5,
    lat: 54.6641,
    lng: -5.9531,
    tags: ['Oversubscribed', 'Waitlist open', 'Popular school'],
    admissionsCriteria: [
      { priority: 1, title: 'Statutory SEN placement', description: 'Children with a statement of special educational needs naming this nursery.' },
      { priority: 2, title: 'Siblings attending the primary school', description: 'Children with a sibling currently in Primary 1–7 of the linked primary school.' },
      { priority: 3, title: 'Catchment area residents', description: 'Children living within 1.5 miles of the school.' },
      { priority: 4, title: 'Remaining applicants', description: 'Distance from home to school (nearest first).' },
    ],
    icon: '🌈',
    color: '#F5F3FF',
    createdAt: '2025-01-01',
    updatedAt: '2025-06-01',
  },
  {
    id: 'npf-004',
    name: 'Happy Minds Pre-School',
    area: 'Castlereagh',
    postcode: 'BT6 8LN',
    address: '45 Castlereagh Road, Belfast BT6 8LN',
    phone: '028 9048 3456',
    email: 'office@happyminds.co.uk',
    type: 'catholic',
    sessionType: 'part-time',
    sessions: 'Afternoon only (12:30pm–3:30pm)',
    ageMin: 3,
    ageMax: 4,
    spacesAvailable: 4,
    waitlistOpen: false,
    nextIntake: 'September 2025',
    deFunded: true,
    rating: 4.6,
    lat: 54.5701,
    lng: -5.9105,
    tags: ['Catholic maintained', 'Sibling priority', 'Faith school'],
    admissionsCriteria: [
      { priority: 1, title: 'Catholic children with siblings at the school', description: 'Catholic children who have a brother or sister currently enrolled.' },
      { priority: 2, title: 'Other Catholic children', description: 'Catholic children without a sibling connection, ranked by distance.' },
      { priority: 3, title: 'Children of other Christian denominations', description: 'Applicants from other Christian backgrounds, by distance.' },
      { priority: 4, title: 'All other children', description: 'All remaining applicants by distance.' },
    ],
    icon: '😊',
    color: '#F0FDF4',
    createdAt: '2025-01-01',
    updatedAt: '2025-06-01',
  },
  {
    id: 'npf-005',
    name: 'Tiny Tots Nursery',
    area: 'Shore Road',
    postcode: 'BT15 3QR',
    address: '102 Shore Road, Belfast BT15 3QR',
    phone: '028 9077 7890',
    email: 'info@tinytots-belfast.co.uk',
    website: 'https://tinytots-belfast.co.uk',
    type: 'private',
    sessionType: 'full-time',
    sessions: 'Full Day (7:30am–6:30pm)',
    ageMin: 1,
    ageMax: 3,
    spacesAvailable: 8,
    waitlistOpen: false,
    nextIntake: 'Ongoing enrolment',
    deFunded: false,
    rating: 4.7,
    lat: 54.6302,
    lng: -5.9371,
    tags: ['Private provider', 'No catchment', 'Babies welcome', 'Flexible hours'],
    admissionsCriteria: [
      { priority: 1, title: 'Open admissions', description: 'No catchment area. All children aged 1–3 years are welcome to apply.' },
      { priority: 2, title: 'Allocation by application date', description: 'Places are allocated strictly in the order applications are received.' },
      { priority: 3, title: 'Sibling discount available', description: 'Families with two or more children enrolled receive a 10% sibling discount on fees.' },
    ],
    icon: '⭐',
    color: '#FFF7ED',
    createdAt: '2025-01-01',
    updatedAt: '2025-06-01',
  },
  {
    id: 'npf-006',
    name: 'Bright Stars Pre-School',
    area: 'Knock',
    postcode: 'BT5 6LE',
    address: '27 Knock Road, Belfast BT5 6LE',
    phone: '028 9065 2345',
    email: 'reception@brightstars.ni.sch.uk',
    type: 'state',
    sessionType: 'part-time',
    sessions: 'Morning only (9:00am–11:30am)',
    ageMin: 3,
    ageMax: 4,
    spacesAvailable: 2,
    waitlistOpen: false,
    nextIntake: 'September 2025',
    deFunded: true,
    rating: 4.4,
    lat: 54.5839,
    lng: -5.8939,
    tags: ['State controlled', 'Within catchment', 'DE funded'],
    admissionsCriteria: [
      { priority: 1, title: 'Children with SEN statements', description: 'Statutory placements take absolute priority.' },
      { priority: 2, title: 'Catchment area residents with siblings', description: 'Children living in catchment who also have a sibling at the school.' },
      { priority: 3, title: 'Catchment area residents', description: 'All other children living within the catchment boundary.' },
      { priority: 4, title: 'Out-of-catchment applicants', description: 'Children from outside catchment, ranked by proximity.' },
    ],
    icon: '⚡',
    color: '#FFFBEB',
    createdAt: '2025-01-01',
    updatedAt: '2025-06-01',
  },
  {
    id: 'npf-007',
    name: 'Little Lambs Nursery',
    area: 'Finaghy',
    postcode: 'BT10 0NF',
    address: '19 Finaghy Road South, Belfast BT10 0NF',
    phone: '028 9062 0987',
    email: 'info@littlelambs.co.uk',
    type: 'private',
    sessionType: 'full-time',
    sessions: 'Full Day (8:00am–5:30pm)',
    ageMin: 2,
    ageMax: 4,
    spacesAvailable: 5,
    waitlistOpen: false,
    nextIntake: 'September 2025',
    deFunded: false,
    rating: 4.6,
    lat: 54.5581,
    lng: -5.9985,
    tags: ['Church of Ireland', 'Sibling priority', 'Christian ethos'],
    admissionsCriteria: [
      { priority: 1, title: 'Children of Church of Ireland families with siblings', description: 'Church of Ireland families with an existing connection to the school.' },
      { priority: 2, title: 'Other Church of Ireland children', description: 'Children from Church of Ireland families without a sibling connection.' },
      { priority: 3, title: 'Children of other denominations', description: 'Christian children from other denominations.' },
      { priority: 4, title: 'All remaining applicants', description: 'All other children by date of application.' },
    ],
    icon: '🐑',
    color: '#F0FDF4',
    createdAt: '2025-01-01',
    updatedAt: '2025-06-01',
  },
  {
    id: 'npf-008',
    name: 'Curiosity Corner',
    area: 'Stranmillis',
    postcode: 'BT9 5AH',
    address: '5 Stranmillis Road, Belfast BT9 5AH',
    phone: '028 9066 1212',
    email: 'hello@curiositycorner.co.uk',
    website: 'https://curiositycorner.co.uk',
    type: 'montessori',
    sessionType: 'full-time',
    sessions: 'Full Day (8:00am–5:30pm)',
    ageMin: 2,
    ageMax: 5,
    spacesAvailable: 3,
    waitlistOpen: false,
    nextIntake: 'Ongoing enrolment',
    deFunded: false,
    rating: 4.9,
    lat: 54.5762,
    lng: -5.9412,
    tags: ['Montessori method', 'Open enrolment', 'Child-led learning'],
    admissionsCriteria: [
      { priority: 1, title: 'Open admissions – no catchment area', description: 'All children aged 2–5 are welcome to apply regardless of where they live.' },
      { priority: 2, title: 'Date of application', description: 'Applications are processed strictly in order received. Early application is recommended.' },
      { priority: 3, title: 'Sibling priority', description: 'Where two applications share the same date, siblings of current pupils take precedence.' },
    ],
    icon: '🔍',
    color: '#EFF6FF',
    createdAt: '2025-01-01',
    updatedAt: '2025-06-01',
  },
  {
    id: 'npf-009',
    name: 'Meadow View Pre-School',
    area: 'Dundonald',
    postcode: 'BT16 1XW',
    address: '67 Old Dundonald Road, Dundonald BT16 1XW',
    phone: '028 9048 6543',
    email: 'admin@meadowview.co.uk',
    type: 'state',
    sessionType: 'part-time',
    sessions: 'Morning (9–12) & Afternoon (12:30–3:30)',
    ageMin: 3,
    ageMax: 4,
    spacesAvailable: 7,
    waitlistOpen: false,
    nextIntake: 'September 2025',
    deFunded: true,
    rating: 4.5,
    lat: 54.5722,
    lng: -5.8533,
    tags: ['State controlled', 'Open enrolment', 'Good Ofsted'],
    admissionsCriteria: [
      { priority: 1, title: 'SEN statutory placements', description: 'Children with a statement of special educational needs.' },
      { priority: 2, title: 'Looked-after children', description: 'Children in the care of the local authority.' },
      { priority: 3, title: 'Siblings of current pupils', description: 'Children with an existing sibling connection to the school.' },
      { priority: 4, title: 'Open enrolment by distance', description: 'All other children, allocated by shortest distance from home to school gate.' },
    ],
    icon: '🌿',
    color: '#F0FDF4',
    createdAt: '2025-01-01',
    updatedAt: '2025-06-01',
  },
  {
    id: 'npf-010',
    name: 'Wee Wonders Nursery',
    area: 'Ballynafeigh',
    postcode: 'BT7 3HS',
    address: '33 Ormeau Embankment, Belfast BT7 3HS',
    phone: '028 9064 5678',
    email: 'office@weewonders.co.uk',
    type: 'catholic',
    sessionType: 'part-time',
    sessions: 'Morning only (9:00am–12:00pm)',
    ageMin: 3,
    ageMax: 4,
    spacesAvailable: 1,
    waitlistOpen: true,
    nextIntake: 'January 2026',
    deFunded: true,
    rating: 4.7,
    lat: 54.5681,
    lng: -5.9201,
    tags: ['Catholic maintained', 'Very popular', 'Waitlist open'],
    admissionsCriteria: [
      { priority: 1, title: 'Catholic children with siblings', description: 'Catholic baptised children who have a sibling currently attending.' },
      { priority: 2, title: 'Catholic children – catchment', description: 'Catholic children within the school catchment area.' },
      { priority: 3, title: 'Catholic children – out of catchment', description: 'Catholic children from outside the catchment, by distance.' },
      { priority: 4, title: 'All other children', description: 'Non-Catholic children, by distance.' },
    ],
    icon: '🌟',
    color: '#FEF3C7',
    createdAt: '2025-01-01',
    updatedAt: '2025-06-01',
  },
  {
    id: 'npf-011',
    name: 'Cedar Tree Nursery',
    area: 'Antrim Road',
    postcode: 'BT14 6RY',
    address: '201 Antrim Road, Belfast BT14 6RY',
    phone: '028 9074 3321',
    email: 'info@cedartree.co.uk',
    website: 'https://cedartree.co.uk',
    type: 'private',
    sessionType: 'full-time',
    sessions: 'Full Day (7:00am–7:00pm)',
    ageMin: 2,
    ageMax: 4,
    spacesAvailable: 9,
    waitlistOpen: false,
    nextIntake: 'Ongoing enrolment',
    deFunded: false,
    rating: 4.8,
    lat: 54.6102,
    lng: -5.9601,
    tags: ['Private provider', 'Extended hours', 'No catchment', 'Flexible sessions'],
    admissionsCriteria: [
      { priority: 1, title: 'Open admissions', description: 'All children aged 2–4 are welcome. No catchment restrictions apply.' },
      { priority: 2, title: 'First come, first served', description: 'Places are allocated in the order completed applications are received.' },
    ],
    icon: '🌲',
    color: '#F0FDF4',
    createdAt: '2025-01-01',
    updatedAt: '2025-06-01',
  },
  {
    id: 'npf-012',
    name: 'Kiddies Kingdom',
    area: 'Ormeau Road',
    postcode: 'BT7 1FH',
    address: '154 Ormeau Road, Belfast BT7 1FH',
    phone: '028 9064 9900',
    email: 'info@kiddieskingdom.co.uk',
    type: 'integrated',
    sessionType: 'full-time',
    sessions: 'Full Day (8:30am–5:30pm)',
    ageMin: 3,
    ageMax: 5,
    spacesAvailable: 4,
    waitlistOpen: false,
    nextIntake: 'September 2025',
    deFunded: true,
    rating: 4.3,
    lat: 54.5749,
    lng: -5.9271,
    tags: ['Integrated', 'Open enrolment', 'Cross-community'],
    admissionsCriteria: [
      { priority: 1, title: 'Children from Protestant and Catholic backgrounds', description: 'Integrated schools aim to maintain a balance of approximately 40%/40%/20% (Protestant/Catholic/Other).' },
      { priority: 2, title: 'Siblings of current pupils', description: 'Children with a sibling already attending, subject to the denominational balance requirement.' },
      { priority: 3, title: 'All other children', description: 'Remaining places allocated to maintain the integrated balance, then by distance.' },
    ],
    icon: '👑',
    color: '#F5F3FF',
    createdAt: '2025-01-01',
    updatedAt: '2025-06-01',
  },
  {
    id: 'npf-013',
    name: 'Stepping Stones Pre-School',
    area: 'Glengormley',
    postcode: 'BT36 6FD',
    address: '8 Church Road, Glengormley BT36 6FD',
    phone: '028 9083 7756',
    email: 'office@steppingstones.ni.sch.uk',
    type: 'state',
    sessionType: 'part-time',
    sessions: 'Afternoon only (12:30pm–3:30pm)',
    ageMin: 3,
    ageMax: 4,
    spacesAvailable: 5,
    waitlistOpen: false,
    nextIntake: 'September 2025',
    deFunded: true,
    rating: 4.6,
    lat: 54.6769,
    lng: -6.0011,
    tags: ['State controlled', 'Sibling priority', 'Good rating'],
    admissionsCriteria: [
      { priority: 1, title: 'Siblings of current pupils', description: 'Children with a sibling in any year group of the primary school.' },
      { priority: 2, title: 'Children of staff', description: 'Children whose parent/guardian is a full-time employee of the school.' },
      { priority: 3, title: 'Catchment area children', description: 'All children residing within the defined catchment area.' },
      { priority: 4, title: 'All other applicants', description: 'Remaining applicants by distance to school gate.' },
    ],
    icon: '🪨',
    color: '#FFF7ED',
    createdAt: '2025-01-01',
    updatedAt: '2025-06-01',
  },
  {
    id: 'npf-014',
    name: 'Bluebell Nursery School',
    area: 'East Belfast',
    postcode: 'BT4 2PQ',
    address: '44 Upper Newtownards Road, Belfast BT4 2PQ',
    phone: '028 9065 4321',
    email: 'admin@bluebell-nursery.co.uk',
    type: 'state',
    sessionType: 'part-time',
    sessions: 'Morning only (9:00am–11:30am)',
    ageMin: 3,
    ageMax: 4,
    spacesAvailable: 2,
    waitlistOpen: false,
    nextIntake: 'September 2025',
    deFunded: true,
    rating: 4.5,
    lat: 54.5971,
    lng: -5.8952,
    tags: ['State controlled', 'Within catchment', 'Morning sessions'],
    admissionsCriteria: [
      { priority: 1, title: 'SEN placements', description: 'Children with a current statement of special educational needs.' },
      { priority: 2, title: 'Siblings within catchment', description: 'Children with a sibling at the school who also live within catchment.' },
      { priority: 3, title: 'Catchment residents', description: 'All other catchment children by distance.' },
      { priority: 4, title: 'Out-of-catchment', description: 'Children outside catchment, nearest first.' },
    ],
    icon: '🔔',
    color: '#EFF6FF',
    createdAt: '2025-01-01',
    updatedAt: '2025-06-01',
  },
  {
    id: 'npf-015',
    name: 'Growing Minds Nursery',
    area: 'Malone',
    postcode: 'BT9 6RR',
    address: '72 Malone Road, Belfast BT9 6RR',
    phone: '028 9068 1122',
    email: 'hello@growingminds.co.uk',
    website: 'https://growingminds.co.uk',
    type: 'waldorf',
    sessionType: 'full-time',
    sessions: 'Full Day (8:00am–6:00pm)',
    ageMin: 2,
    ageMax: 5,
    spacesAvailable: 11,
    waitlistOpen: false,
    nextIntake: 'Ongoing enrolment',
    deFunded: false,
    rating: 4.9,
    lat: 54.5621,
    lng: -5.9452,
    tags: ['Waldorf approach', 'Private provider', 'Nature-based', 'No screen time'],
    admissionsCriteria: [
      { priority: 1, title: 'Open admissions', description: 'All children aged 2–5 welcome. No geographical restrictions.' },
      { priority: 2, title: 'Application date', description: 'Places offered in order of application. Rolling admissions throughout the year.' },
      { priority: 3, title: 'Sibling priority', description: 'Siblings of currently enrolled children are given waitlist priority if the nursery is full.' },
    ],
    icon: '🧠',
    color: '#F5F3FF',
    createdAt: '2025-01-01',
    updatedAt: '2025-06-01',
  },
  {
    id: 'npf-016',
    name: 'Cloverleaf Pre-School',
    area: 'Ballysillan',
    postcode: 'BT14 7PT',
    address: '91 Ballysillan Road, Belfast BT14 7PT',
    phone: '028 9071 8844',
    email: 'office@cloverleaf.co.uk',
    type: 'state',
    sessionType: 'part-time',
    sessions: 'Morning only (9:00am–12:00pm)',
    ageMin: 3,
    ageMax: 4,
    spacesAvailable: 0,
    waitlistOpen: true,
    nextIntake: 'January 2026',
    deFunded: true,
    rating: 4.4,
    lat: 54.6101,
    lng: -5.9981,
    tags: ['Oversubscribed', 'Sibling priority', 'Waitlist open'],
    admissionsCriteria: [
      { priority: 1, title: 'Siblings of current pupils', description: 'Highest priority given to siblings of children already enrolled.' },
      { priority: 2, title: 'Children within catchment', description: 'Children residing within the school catchment area.' },
      { priority: 3, title: 'All other children', description: 'Remaining applicants ranked by distance.' },
    ],
    icon: '🍀',
    color: '#F0FDF4',
    createdAt: '2025-01-01',
    updatedAt: '2025-06-01',
  },
  {
    id: 'npf-017',
    name: 'Sunbeam Nursery',
    area: 'Windsor',
    postcode: 'BT12 7DB',
    address: '16 Windsor Avenue, Belfast BT12 7DB',
    phone: '028 9024 5566',
    email: 'info@sunbeam-nursery.co.uk',
    type: 'catholic',
    sessionType: 'part-time',
    sessions: 'Morning (9–12) & Afternoon (12:30–3:30)',
    ageMin: 3,
    ageMax: 4,
    spacesAvailable: 3,
    waitlistOpen: false,
    nextIntake: 'September 2025',
    deFunded: true,
    rating: 4.6,
    lat: 54.5779,
    lng: -5.9601,
    tags: ['Catholic maintained', 'Sibling priority', 'Faith school'],
    admissionsCriteria: [
      { priority: 1, title: 'Catholic children – siblings enrolled', description: 'Catholic children with a brother or sister currently in the school.' },
      { priority: 2, title: 'Catholic children – catchment', description: 'Baptised Catholic children from the parish catchment area.' },
      { priority: 3, title: 'Catholic children – other areas', description: 'Catholic children from outside the parish catchment.' },
      { priority: 4, title: 'All other children', description: 'Children of any faith or none, by distance.' },
    ],
    icon: '☀️',
    color: '#FFFBEB',
    createdAt: '2025-01-01',
    updatedAt: '2025-06-01',
  },
  {
    id: 'npf-018',
    name: 'ABC Nursery School',
    area: 'Balmoral',
    postcode: 'BT10 0AB',
    address: '38 Balmoral Avenue, Belfast BT10 0AB',
    phone: '028 9030 1122',
    email: 'info@abc-nursery.co.uk',
    website: 'https://abc-nursery.co.uk',
    type: 'private',
    sessionType: 'full-time',
    sessions: 'Full Day (7:30am–6:00pm)',
    ageMin: 2,
    ageMax: 5,
    spacesAvailable: 6,
    waitlistOpen: false,
    nextIntake: 'Ongoing enrolment',
    deFunded: false,
    rating: 4.7,
    lat: 54.5601,
    lng: -5.9891,
    tags: ['Private provider', 'No catchment', 'Flexible', 'All year round'],
    admissionsCriteria: [
      { priority: 1, title: 'Open admissions – no restrictions', description: 'All children aged 2–5 can apply. No catchment, faith, or distance criteria.' },
      { priority: 2, title: 'First come, first served', description: 'Applications processed in order of receipt.' },
    ],
    icon: '🔤',
    color: '#FEF3C7',
    createdAt: '2025-01-01',
    updatedAt: '2025-06-01',
  },
  {
    id: 'npf-019',
    name: 'Playful Panda Nursery',
    area: 'Carryduff',
    postcode: 'BT8 8EL',
    address: '5 Saintfield Road, Carryduff BT8 8EL',
    phone: '028 9081 3344',
    email: 'info@playfulpanda.co.uk',
    website: 'https://playfulpanda.co.uk',
    type: 'private',
    sessionType: 'full-time',
    sessions: 'Full Day (8:00am–6:00pm)',
    ageMin: 3,
    ageMax: 5,
    spacesAvailable: 7,
    waitlistOpen: false,
    nextIntake: 'Ongoing enrolment',
    deFunded: false,
    rating: 4.8,
    lat: 54.5301,
    lng: -5.9121,
    tags: ['Open enrolment', 'Private provider', 'Award winning'],
    admissionsCriteria: [
      { priority: 1, title: 'Open admissions', description: 'All children aged 3–5 are welcome to apply regardless of postcode.' },
      { priority: 2, title: 'Date of application', description: 'All places allocated in order received. No waiting list if spaces exist.' },
    ],
    icon: '🐼',
    color: '#F0FDF4',
    createdAt: '2025-01-01',
    updatedAt: '2025-06-01',
  },
  {
    id: 'npf-020',
    name: 'Dreaming Daisies Pre-School',
    area: 'Newtownards Road',
    postcode: 'BT4 1AX',
    address: '77 Newtownards Road, Belfast BT4 1AX',
    phone: '028 9045 6789',
    email: 'admin@dreamingdaisies.co.uk',
    type: 'state',
    sessionType: 'part-time',
    sessions: 'Morning only (9:00am–12:00pm)',
    ageMin: 3,
    ageMax: 4,
    spacesAvailable: 4,
    waitlistOpen: false,
    nextIntake: 'September 2025',
    deFunded: true,
    rating: 4.5,
    lat: 54.5991,
    lng: -5.9021,
    tags: ['State controlled', 'Within catchment', 'DE funded'],
    admissionsCriteria: [
      { priority: 1, title: 'SEN statutory placements', description: 'Children with a statement of special educational needs.' },
      { priority: 2, title: 'Siblings and catchment residents', description: 'Children with siblings enrolled AND living in catchment.' },
      { priority: 3, title: 'Catchment only', description: 'Children from the catchment without a sibling connection.' },
      { priority: 4, title: 'All remaining applicants', description: 'By distance from school, nearest first.' },
    ],
    icon: '🌼',
    color: '#FFFBEB',
    createdAt: '2025-01-01',
    updatedAt: '2025-06-01',
  },
]
